[package]
name = "bevy-pixels"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A pixel based tilemap for bevy!"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"
