name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Publish
        run : |
          VERSION="${GITHUB_REF#refs/*/}" make publish
          env:
              CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_KEY }}
